### ISSUE TITLE
tilesize: wrong compile flag

### ISSUE THREAD

**Issue by sjanssen2** [jlab/gapc#205]
Hi @fymue,
it just came to my mind that the new tile size parameter does not impact CYK in general, but only the multithread version, i.e. if user compile their code with the `_OPENMP` flag set. Shouldn't that be the better test for exposing the parameter, instead of your new `CYK_CODEGEN` flag? Or am I missing something here? My fault in the discussion of the PR #204  :-/
https://github.com/jlab/gapc/blob/9478cc0f79c3b454cf029572740aa1cba8a3426b/rtlib/generic_opts.hh#L203-L208

**Comment by fymue** [comment]
Yes that would indeed be the better/correct test. I missed that too. We can fix this by changing every `#ifdef CYK_CODEGEN` line to `#if defined(CYK_CODEGEN) && defined(_OPENMP)`. Do you want me to do this or can you do this really quick? I would need to open a new PR for this.

**Comment by sjanssen2** [comment]
New PR is fine :-) But do we need CYK_CODEGEN at All?

Fynn Mürmanns ***@***.***> schrieb am Fr., 19. Mai 2023,
12:02:

**Comment by fymue** [comment]
I would still also check for `CYK_CODEGEN` to cover the case where we might use OpenMP for something in programs with Unger style codegen. Alright, I will open a new PR for this then.

**Comment by sjanssen2** [comment]
I don't See how parallelism could work with Unger due to the checks for
celle computation. I'd prefer to remove cyk_codegen (for now). Sorry for
the Extra work.

Fynn Mürmanns ***@***.***> schrieb am Fr., 19. Mai 2023,
12:19:

**Comment by sjanssen2** [comment]
addressed and solved by #206
