### ISSUE TITLE
use OUTSIDE_ALL

### ISSUE THREAD

**Issue by sjanssen2** [jlab/gapc#217]
Hi @fymue can you give me a hint how I can replace the hard coded ALL in the following line with the value of 
https://github.com/jlab/gapc/blob/06a688dce38b679bdde8f68533d2bdf19bc83715/src/gapc.cc#L110
`OUTSIDE_ALL`: https://github.com/jlab/gapc/blob/06a688dce38b679bdde8f68533d2bdf19bc83715/src/outside/grammar_transformation.hh#L43 ?

**Comment by fymue** [comment]
Sure. You can simply wrap the help msg in an `std::string` and concatenate `OUTSIDE_ALL` with that string, like so:
```
("outside_grammar", po::value< std::vector<std::string> >(),
 std::string("generate an outside version of the grammar and report outside results 
 for an inside non-terminal. Provide multiple times for lists of non-terminals or type \" + 
 OUTSIDE_ALL + \" to report results for all non-terminals.").c_str())

I can't tell if `OUTSIDE_ALL` is going to be visible in `gapc.cc` though. If not, you could just turn it into a macro.

**Comment by fymue** [comment]
You also might need to wrap `OUTSIDE_ALL` in a `std::string`. I'm not sure if `operator+` is overloaded for `const char*`, so you might not be able to concatenate the strings like this unless one of the strings is an actual `std::string`.

**Comment by sjanssen2** [comment]
it needed to "double wrap", but it works like a charm. Thank you!
